# Generated by Django 3.1.2 on 2020-10-30 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('release', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(db_column='relation', max_length=30)),
                ('timestamp', models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now)),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.PROTECT, to='search.book')),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.PROTECT, to='search.person')),
            ],
        ),
    ]
