# Generated by Django 3.1.2 on 2020-10-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20201030_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssociatedPeroon',
            new_name='AssociatedPerson',
        ),
    ]
